steps:
  # Paso 1: Compilar el proyecto con Maven
  - name: 'maven:3.8.5-openjdk-17'
    entrypoint: 'mvn'
    args: ['clean', 'package', '-DskipTests=true']

  # Paso 2: Construir la imagen Docker
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/magnetic-energy-461823-a0/clinicarepo/clinica365', '.']

  # Paso 3: Subir la imagen al Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/magnetic-energy-461823-a0/clinicarepo/clinica365']

  # Paso 4: Desplegar automáticamente en Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'clinica365-service'
      - '--image=us-central1-docker.pkg.dev/magnetic-energy-461823-a0/clinicarepo/clinica365'
      - '--region=us-central1'
      - '--platform=managed'
      - '--allow-unauthenticated'

images:
  - 'us-central1-docker.pkg.dev/magnetic-energy-461823-a0/clinicarepo/clinica365'
