steps:
  # Paso 1: Compilar el proyecto con Maven y generar el .jar
  - name: 'maven:3.8.5-openjdk-17'
    entrypoint: 'mvn'
    args: ['clean', 'package', '-DskipTests']

  # Paso 2: Construir la imagen Docker usando el Dockerfile
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t', 'us-central1-docker.pkg.dev/magnetic-energy-461823-a0/clinicarepo/clinica365',
      '.'
    ]

  # Paso 3: Subir la imagen a Google Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'push',
      'us-central1-docker.pkg.dev/magnetic-energy-461823-a0/clinicarepo/clinica365'
    ]

images:
  - 'us-central1-docker.pkg.dev/magnetic-energy-461823-a0/clinicarepo/clinica365'
