steps:
  # Paso 1: compilar el proyecto con Maven
  - name: 'maven:3.8.5-openjdk-17'
    entrypoint: 'mvn'
    args: ['clean', 'install']

  # Paso 2: construir la imagen Docker
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t', 'us-central1-docker.pkg.dev/magnetic-energy-461823-a0/clinicarepo/clinica365',
      '.'
    ]

  # Paso 3: subir la imagen al Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'push',
      'us-central1-docker.pkg.dev/magnetic-energy-461823-a0/clinicarepo/clinica365'
    ]

images:
  - 'us-central1-docker.pkg.dev/magnetic-energy-461823-a0/clinicarepo/clinica365'
