name: Deploy to Cloud Run

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Configure Docker to use Google Artifact Registry
        run: gcloud auth configure-docker us-central1-docker.pkg.dev

      - name: Build Docker image
        run: docker build -t us-central1-docker.pkg.dev/clinica365-461902/clinica365-repo/clinica365-services:$GITHUB_SHA .

      - name: Push Docker image
        run: docker push us-central1-docker.pkg.dev/clinica365-461902/clinica365-repo/clinica365-services:$GITHUB_SHA

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy clinica365-services \
            --image us-central1-docker.pkg.dev/clinica365-461902/clinica365-repo/clinica365-services:$GITHUB_SHA \
            --region us-central1 \
            --platform managed \
            --allow-unauthenticated
          
          
